import Head from "next/head";
import Navbar from "@/components/Navbar";
import About from "@/components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yasuaki Kumazaki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-stone-500 px-10 font-helvetica_neue">
        <section className="min-h-screen">
          <Navbar />
          <About />
        </section>
      </main>
    </div>
  );
}
